### ISSUE TITLE
go run examples/mcast/server/main.go : no buffer space available

### ISSUE THREAD

**Issue by boaks** [go-ocf/go-coap#108]
I would like to test the multicast server. If I start it, I get

> go run examples/mcast/server/main.go 
> 2020/03/26 15:17:07 setsockopt: no buffer space available
> exit status 1
 
Is there something I must setup before?

**Comment by jkralik** [comment]
Pls could you describe your system ? I'm not able to reproduce it at Ubuntu 16 and Windows 10.

**Comment by boaks** [comment]
Ubuntu 18.04, "go version go1.14 linux/amd64"

**Comment by boaks** [comment]
After cleaning up my network interfaces (microk8s create some veth.. too much), it starts without the error message. Seems the failure was caused on too many network interfaces on my side.
