### ISSUE TITLE
mcast server - received RST processed as request?

### ISSUE THREAD

**Issue by boaks** [go-ocf/go-coap#110]
Testing with the mcast server, I got some irritating behavior:

When I reject a message by sending a RST, that seems to be interpreted as request and a response is sent back. Usually I would expect, that a RST is either ignored or stops some messages from being send again. With the behavior above, the RST seems to achieve the opposite of the intention (stop send that message turns into send new response).

Maybe it's possible to improve the request handler to only forward request (and no ACK/RST/responses as requests). Such a request is [either CON or NON message (never ACK nor RST)](https://tools.ietf.org/html/rfc7252#page-23) and the [code has class 0](https://tools.ietf.org/html/rfc7252#page-16).

(Just to mention: the reason for sending RST seems to be, that the endpoint's port is changing (from mcast receiver 5688 to some other port when sending the response). I'm not sure, why this should be accepted, even if the RFC 7252 seems to address that port change. I'm currently try to clarify that. But anyway, processing a RST as request and sending back a response seems to be very irritating.)

**Comment by jkralik** [comment]
Will be fixed in v2

**Comment by boaks** [comment]
I'm in branch v2, on commit a31f765

Now the messages are received on 5683 and the response is also send from that port.
Great!

If I reject such a response (just for testing), I still get a next response with 4.04

RST (for test):
0000   70 00 d9 d8

Next NON response.
0000   50 84 d9 d9

In my opinion, ACK o RST should not result in a next empty NON Response.
