### ISSUE TITLE
Client connection method APIs should allow setting of CoAP options

### ISSUE THREAD

**Issue by hjames9** [go-ocf/go-coap#125]
@jkralik Since the Message object isn't exposed on the method APIs e.g. GetWithContext, PostWithContext, PutWithContext, etc. there's currently no way to use those APIs and set any of the CoAP options such as URIQuery, ETag, etc.

In addition, if you attempt to build a confirmable Message directly and use WriteMsgWithContext, it seems to have strange behavior of the server and client constantly sending messages back and forth without stopping (presumably some sort of retry logic).

			message := conn.NewMessage(coap.MessageParams{
				Type:      coap.Confirmable,
				Code:      codes.GET,
				MessageID: uint16(rand.Intn(65535)),
				Token:     []byte{123},
			})
			message.SetOption(coap.ContentFormat, coap.TextPlain)
			message.SetURIQuery("APIKEY=123456")
			message.SetPathString("/test")

			ctx, cancel := context.WithTimeout(context.Background(), time.Second)
			defer cancel()

			err := conn.WriteMsgWithContext(ctx, message)
			if err != nil {
				log.Error().Msgf("Error sending request: %v", err)
				break
			}

**Comment by jkralik** [comment]
Pls could you try to use go-coap/v2 . This version allows you to set any option.

**Comment by beriberikix** [comment]
I was able to confirm that this works in v2!

**Comment by jkralik** [comment]
Thx for info ;).

**Comment by beriberikix** [comment]
I'm trying to put together a sample using the new V2 syntax and I'm finding a few different ways to construct a request. If I create a connection using `udp.Dial()`, how should I generate the message options for say a `Get()`? 

Forgive me if that's a naive q, still a novice Gopher here :)
