### ISSUE TITLE
middleware.go comment bug mentions HTTP

### ISSUE THREAD

**Issue by beriberikix** [go-ocf/go-coap#127]
`middleware.go` in v2 has a [comment](https://github.com/go-ocf/go-coap/blob/f73ac2c10ec3dd0c47ae9c65a547cf54e7e053a0/mux/middleware.go#L3):
```
// MiddlewareFunc is a function which receives an http.Handler and returns another http.Handler.
// Typically, the returned handler is a closure which does something with the http.ResponseWriter and http.Request passed
// to it, and then calls the handler passed as parameter to the MiddlewareFunc.
```
I believe that it is a copy-paste error since it looks exactly like the comment in [gorilla mux](https://github.com/gorilla/mux/blob/master/middleware.go#L8).

Is that correct? It'll be super-easy to fix.

**Comment by jkralik** [comment]
Yes. I want to take features from the project which can be used with COAP. For now it was middleware.
