### ISSUE TITLE
client can not recreate connection with  coap server

### ISSUE THREAD

**Issue by ls327782081** [go-ocf/go-coap#131]
i can not find how to release ClientConn in server's conns.when client down, the server can not write response to client than it use cancle function but the ClientConn still in server's conns. The next time, client recreate connection with the server, the server do not create ClientConn but get it  from server's conns,it cause ClientConn's context is cancle

**Comment by jkralik** [comment]
Hi.

- How did you initialize server - which paramters -> Is it keepalive enabled ?
- Could you create a test for reproduce the issue / a sample code ?

Thx

**Comment by ls327782081** [comment]
i set keepalive nil 
	s := udp.NewServer(udp.WithMux(mux), udp.WithTransmission(time.Duration(transmissionTimeout)*time.Second, 2*time.Duration(transmissionTimeout)*time.Second, transmissionMaxRetrans), udp.WithBlockwise(true, blockwise.SZX1024, time.Duration(transmissionTimeout)*time.Second), udp.WithContext(ctx))

**Comment by ls327782081** [comment]
s := udp.NewServer(udp.WithMux(mux), udp.WithTransmission(time.Duration(transmissionTimeout)*time.Second, 2*time.Duration(transmissionTimeout)*time.Second, transmissionMaxRetrans), udp.WithBlockwise(true, blockwise.SZX1024, time.Duration(transmissionTimeout)*time.Second), udp.WithContext(ctx), udp.WithKeepAlive(nil))

**Comment by jkralik** [comment]
I found the issue and I created fix for that in branch `fixOfCloseSessions` . Pls could you check if it is solve the issue ?

**Comment by ls327782081** [comment]
this is been solved.😊
