### ISSUE TITLE
Combined Client and Server possible?

### ISSUE THREAD

**Issue by c1728p9** [go-ocf/go-coap#133]
It is possible to have a connection where both sides can initiate a request? I'm wanting to use this library to handle LWM2M bootstrapping which needs requests in both directions, but I didn't see a way to do this.

Example LWM2M bootstrap flow:

![image](https://user-images.githubusercontent.com/2916772/85354342-f7645880-b4cf-11ea-8776-caa3fe6b7a4f.png)

**Comment by jkralik** [comment]
Hi
I think, you need to set a router to the client:
```
func handleA(w mux.ResponseWriter, r *mux.Message) {
	log.Printf("got message in handleA:  %+v from %v\n", r, w.Client().RemoteAddr())
	err := w.SetResponse(codes.Changed, message.TextPlain, bytes.NewReader([]byte("hello world")))
	if err != nil {
		log.Printf("cannot set response: %v", err)
	}
}
func main() {
        m := mux.NewRouter()
	m.Handle("/0/1", mux.HandlerFunc(handleA))
	co, err := dtls.Dial("localhost:5688", &piondtls.Config{
		PSK: func(hint []byte) ([]byte, error) {
			fmt.Printf("Server's hint: %s \n", hint)
			return []byte{0xAB, 0xC1, 0x23}, nil
		},
		PSKIdentityHint: []byte("Pion DTLS Client"),
		CipherSuites:    []piondtls.CipherSuiteID{piondtls.TLS_PSK_WITH_AES_128_CCM_8},
	}, dtls.WithMux(m))
        ...
}
```

**Comment by c1728p9** [comment]
Thanks for your help @jkralik, with this info I was able to receive the bootstrapping messages I needed.
