### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by slaesh** [go-ocf/go-coap#135]
go get github.com/go-ocf/go-coap
../../../go/src/github.com/go-ocf/go-coap/message/message.go:8:2: code in directory /home/sascha/go/src/github.com/go-ocf/go-coap/message/codes expects import "github.com/go-ocf/go-coap/codes"

**Comment by slaesh** [comment]
go version
go version go1.14.4 linux/amd64

**Comment by slaesh** [comment]
go get github.com/go-ocf/go-coap/v2
package github.com/go-ocf/go-coap/v2: cannot find package "github.com/go-ocf/go-coap/v2" in any of:
        /usr/lib/go/src/github.com/go-ocf/go-coap/v2 (from $GOROOT)
        /home/sascha/go/src/github.com/go-ocf/go-coap/v2 (from $GOPATH)

**Comment by jkralik** [comment]
Hi.
- Do you use `go modules` in your project?
- Do you import it via `import github.com/go-ocf/go-coap/v2` to your golang files ?

**Comment by slaesh** [comment]
... `go mod init ` did the trick .. :)
i am sorry! thanks for your blazing fast answer!!
