### ISSUE TITLE
modifying messge within middleware

### ISSUE THREAD

**Issue by slaesh** [go-ocf/go-coap#136]
hey, i am wondering how i could implement a middleware like "json-body to object" ..
parse it, convert it and EXTEND the message for later use cases. :)

is this actually possible? how?

if not, is this planed?

thanks!

**Comment by jkralik** [comment]
yes it is possible: in middleware you just parse body and then you set object to the context of request - something like:
```
func parseMiddleware(next mux.Handler) mux.Handler {
	return mux.HandlerFunc(func(w mux.ResponseWriter, r *mux.Message) {
                byteValue, _ := ioutil.ReadAll(r.Body)
                var obj interface{}
                json.Unmarshal([]byte(byteValue), &obj)
                r.Context = context.WithValue(r.Context, "parsedObj", obj)
		next.ServeCOAP(w, r)
	})
}
```

**Comment by slaesh** [comment]
amazing!
didn't knew this `context` stuff yet..

thanks!!
