### ISSUE TITLE
Option to disable keep-alive feature

### ISSUE THREAD

**Issue by jdbruijn** [go-ocf/go-coap#139]
Is it currently possible to disable the keep-alive feature (added in #93)? If so I weren't able to find it.

I'm communicating with an embedded device which doesn't have any keep-alive functionality implemented so gets confused with those message, especially when they're coming in between regular messages.

If not possible I'd very much like some configuration to be able to disable this feature, would that be possible? Also, where does this feature come from? I couldn't find anything of it in the RFC 7252.

**Comment by jkralik** [comment]
Yes there is such option: `WithKeepAlive(nil)`   https://pkg.go.dev/github.com/go-ocf/go-coap/v2@v2.0.2/udp?tab=doc#WithKeepAlive

It is mentioned here: https://tools.ietf.org/html/rfc7252#section-1.2 end of part `Reset Message`

**Comment by jdbruijn** [comment]
Thanks for pointing that out, missed that small section of the RFC.

I'm using DTLS, where that option is not available if I'm not mistaken (https://github.com/go-ocf/go-coap/blob/v2.0.2/server.go#L55). The notes you've referred to are specifically for UDP, and I couldn't find a way that I can pass options to the underlying UDP socket of DTLS.
For reference, I'm using go-coap as follows, where it is imported as `coap "github.com/go-ocf/go-coap/v2"`.

```go
	err = coap.ListenAndServeDTLS(
		"udp4",
		fmt.Sprintf(":%v", config.Server.ListenPort),
		&dtlsConfig,
		mux.HandlerFunc(DefaultHandler),
	)
```

**Comment by jkralik** [comment]
So If you want to use options you need to create own ListenAndServe:
```
func ListenAndServe(config Config) error {
        l, err := net.NewDTLSListener("udp4", fmt.Sprintf(":%v", config.Server.ListenPort), &dtlsConfig)
	if err != nil {
		return err
	}
	defer l.Close()
	s := dtls.NewServer(dtls.WithMux(mux.HandlerFunc(DefaultHandler)), dtls.WithKeepAlive(nil))
	return s.Serve(l)
}
```

**Comment by jdbruijn** [comment]
Good to know that I just have to create my own function for that, it worked as expected. Thanks for showing the example!
