### ISSUE TITLE
Add validation against MaxMessageSize before send,receive Message

### ISSUE THREAD

**Issue by jkralik** [go-ocf/go-coap#14]
Add validation against MaxMessageSize before when send,receive Message/payload
- with blockwise
- without blockwise
- add ToBytesLength( to Message that calculate actual size of udpmessage, tcpmessage.

MaxMessageSize with 0 means unlimited.

**Comment by arun1587** [comment]
Is this still open?

**Comment by jkralik** [comment]
Yes. Unless someout implement I will do it in this year.

**Comment by arun1587** [comment]
So we validate the size of request against `peerMaxMessageSize` in `handlePairMsg()` and size of response against `s.srv.MaxMessageSize` in `WriteMsgWithContext()` for the `sessionTCP`. right? .If so, I could create a PR for it.

**Comment by jkralik** [comment]
`peerMaxMessageSize`:
- must be validate it in `blockWiseSession.WriteMsgWithContext, sessionTCP.WriteMsgWithContext`
- is set via CSM message from peer and it's determine maximum message (header+payload) size that can be send to the peer. (whole message that is send via blockwise),
- for UDP it is not supported

`s.srv.MaxMessageSize`:
- must be validate when server read message from TCP/UDP connection: `server.serveUDP , server.serverTCPconnnection`  - (for tcp it is immediately after parse coap header)
- and it must be dynamically check in blockwise via `blockWiseReceiver`

**Comment by arun1587** [comment]
thanks for the clarification. 
`peerMaxMessageSize` if not set in the CSM of peer defaults to `1152`, right ?

> (whole message that is send via blockwise)

I think the limit is for each block and not for whole message as explained in this [section](https://tools.ietf.org/html/rfc8323#section-5.3.1) of RFC8323, no ?

**Comment by jkralik** [comment]
If `peerMaxMessageSize` is not, then peer doesn't limit a message.

You are right. It' s only limit each block.

Hm but i want to somehow limit whole message, because peer can exhaust memory of the server/client.

**Comment by jkralik** [comment]
MaxMessageSize was implemented by https://github.com/go-ocf/go-coap/pull/42
