### ISSUE TITLE
close inactive udp session

### ISSUE THREAD

**Issue by jkralik** [go-ocf/go-coap#16]
in current implementation udp session is hold forever. It's need to define and implement timeout which cause close udp session.

**Comment by akokhanovskyi** [comment]
This also causes `Server.sessionUDPMap` to grow indefinitely. Is the suggested workaround to Close() timed out UDP sessions manually for the time being?

**Comment by jkralik** [comment]
For now yes. You can implement keep-alive to determine  close the udp/tcp session.

**Comment by jkralik** [comment]
Handled by keep-alive feature: https://github.com/go-ocf/go-coap/pull/93
