### ISSUE TITLE
BlockwiseResponseWriter doesn't implement .Write()

### ISSUE THREAD

**Issue by ara4n** [go-ocf/go-coap#18]
I just had some fun trying to work out why blockwise transfers weren't working in a test app where the response was handled by:

```go
func handleA(w coap.ResponseWriter, req *coap.Request) {
	w.SetContentFormat(coap.TextPlain)
	if _, err := w.Write(make([]byte, 96)); err != nil {
		log.Printf("Cannot send response: %v", err)
	}
}
```

The symptoms were that the first block of the response was correctly sent, but the client's request for the second block was silently ignored.

This seems to be because `processResp()` was failing silently due to `resp.Code() != s.expectedCode` - where the response code is a `POST` but the expectedCode is apparently a `Continue`.  However, the correct code for requesting a continuation of a POST is a `POST`, not a `Continue`.

This seems to be due to `Write()` taking completely the wrong path when called on a blockwise transfer; compare:

```
github.com/go-ocf/go-coap.(*blockWiseSession).sendPayload(0xc0001f0010, 0x5f021701, 0x125efc0, 0xc00019a460, 0x1, 0xc0001c3af8, 0x10adc54, 0xc0000aa000)
	/Users/matthew/go/src/github.com/go-ocf/go-coap/blockwise.go:301 +0x34
github.com/go-ocf/go-coap.(*blockWiseSession).Exchange(0xc0001f0010, 0x125efc0, 0xc00019a460, 0x100, 0x3c, 0x14, 0x3ce189)
	/Users/matthew/go/src/github.com/go-ocf/go-coap/blockwise.go:347 +0x246
github.com/go-ocf/go-coap.(*blockWiseSession).WriteMsg(0xc0001f0010, 0x125efc0, 0xc00019a460, 0xc0001c3b40, 0x10adeb0)
	/Users/matthew/go/src/github.com/go-ocf/go-coap/blockwise.go:357 +0xaf
github.com/go-ocf/go-coap.(*ClientCommander).WriteMsg(0xc0001f0040, 0x125efc0, 0xc00019a460, 0x0, 0x28)
	/Users/matthew/go/src/github.com/go-ocf/go-coap/clientcommander.go:106 +0x47
github.com/go-ocf/go-coap.(*responseWriter).WriteMsg(0xc0001aa140, 0x125efc0, 0xc00019a460, 0x1, 0x1)
	/Users/matthew/go/src/github.com/go-ocf/go-coap/responsewriter.go:60 +0x8b
github.com/go-ocf/go-coap.(*responseWriter).Write(0xc0001aa140, 0xc00020e000, 0x60, 0x60, 0x0, 0x0, 0x0)
	/Users/matthew/go/src/github.com/go-ocf/go-coap/responsewriter.go:88 +0xfd
main.handleA(0x125dda0, 0xc0001a2020, 0xc0001aa160)
	/Users/matthew/workspace/go-ocf/go-coap/examples/simple/test/main.go:29 +0xba
github.com/go-ocf/go-coap.HandlerFunc.ServeCOAP(0x1234c88, 0x125dda0, 0xc0001a2020, 0xc0001aa160)
```

with instead calling `WriteMsg()`, which goes straight to a BlockwiseResponseWriter which then does the right thing:

```
github.com/go-ocf/go-coap.(*blockWiseSession).sendPayload(0xc0001c4010, 0xc002021701, 0x125f040, 0xc0000b8730, 0x1, 0x1259e08, 0xc0001a1ba0, 0x1040927)
	/Users/matthew/go/src/github.com/go-ocf/go-coap/blockwise.go:301 +0x34
github.com/go-ocf/go-coap.(*blockWiseResponseWriter).WriteMsg(0xc0000ac068, 0x125f040, 0xc0000b8730, 0x60, 0x60)
	/Users/matthew/go/src/github.com/go-ocf/go-coap/blockwise.go:756 +0x215
main.handleA(0x125de20, 0xc0000ac068, 0xc0000b6520)
	/Users/matthew/workspace/go-ocf/go-coap/examples/simple/test/main.go:24 +0x13c
```

I assume this is because `blockWiseResponseWriter` simply doesn't implement `.Write()`, causing much confusion.

The workaround is to use `.WriteMsg()`, which seems to work:

```go
func handleA(w coap.ResponseWriter, req *coap.Request) {
	resp := w.NewResponse(coap.Content)
	resp.SetOption(coap.ContentFormat, coap.TextPlain)
	resp.SetPayload(make([]byte, 96))
	err := w.WriteMsg(resp)
	if err != nil {
		log.Printf("Cannot write response %v", err)
	}
}
```

Is my reasoning correct here?

**Comment by jkralik** [comment]
Thank you fo report a BUG.

> This seems to be because processResp() was failing silently due to resp.Code() != s.expectedCode - where the response code is a POST but the expectedCode is apparently a Continue. However, the correct code for requesting a continuation of a POST is a POST, not a Continue.

Yes. You are right. I created fix of that: https://github.com/go-ocf/go-coap/pull/19.

**Comment by jkralik** [comment]
Pls could you confirm that fix help you?

**Comment by ara4n** [comment]
many thanks - will check asap. is it correct that .Write() goes to responseWriter but .WriteMsg() goes to blockWiseResponseWriter though? I’d expect that they’d both be handled by the blockwise writer...

**Comment by ara4n** [comment]
right - i confirm that https://github.com/go-ocf/go-coap/pull/19 seems to make `.Write()` work as expected when in blockwise mode, although i don't understand whether this is a workaround or a full solution.

**Comment by ara4n** [comment]
np, thanks for the speedy fix! i think this can be closed now?
