### ISSUE TITLE
add support for DTLS

### ISSUE THREAD

**Issue by jkralik** [go-ocf/go-coap#23]
Extends `type Server struct` about:
- `Net` about "udp-tls/dtls" that 
- configuration for dtls

Initialize DTLS socket and use same code as for udp.
Evaluate libraries: https://github.com/pions/dtls,  https://github.com/bocajim/dtls

Add tests
- dtls server/client
- against  iotivity device.

**Comment by jkralik** [comment]
> Are you planning to add PSK to it?
No. For now I just add mention one implementation.

> I wondered whether https://github.com/bocajim/dtls might be a better bet (on the assumption that it might get upgraded from DTLS/1.0 to DTLS/1.2 in future)?
I add https://github.com/bocajim/dtls to issue for evaluation.

Thx for information.

**Comment by andrerfcsantos** [comment]
Looking forward for the implementation of this feature. Any news on the progress/plans for this?

**Comment by jkralik** [comment]
For now it is not planned because I use TCP/TLS. If there will be lot's of thumbs up or someone who wants to contribute then please create pull request. I will merge it.

**Comment by daenney** [comment]
We're about to land PSK support in pions/dtls#76, starting with TLS_PSK_AES_CCM8 b/c a lot of IoT things use that. We're hoping to see the PR reviewed and merged this week.

**Comment by jkralik** [comment]
Hi. I integrated pion/dtls to go-coap in branch https://github.com/go-ocf/go-coap/tree/dtls. And it will be merge in the near future, but fill free to test it. You can find example: https://github.com/go-ocf/go-coap/tree/dtls/examples/dtls

**Comment by daenney** [comment]
That's awesome, thanks for taking the time to do this! I've just pushed the v1.4.0 tag to pion/dtls so you don't have to depend on master/SHA anymore.

**Comment by jkralik** [comment]
Thx for tag. Branch was merged to the master.
