### ISSUE TITLE
runtime error with empty path resource

### ISSUE THREAD

**Issue by gh0st42** [go-ocf/go-coap#24]
I can't request an empty resource (`co.Get("")`or `co.Get("/")`) which I believe should be possible according to the rfc. Other clients and public test servers such as `coap.me` and `californium.eclipse.org` do respond to these requests.

Here's the stack trace:
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/go-ocf/go-coap.(*MessageBase).SetPathString(0xc00014a000, 0x121f26a, 0x1)
	/Users/gh0st42/go/pkg/mod/github.com/go-ocf/go-coap@v0.0.0-20181204124429-322e1f81bfdc/message.go:594 +0xac
github.com/go-ocf/go-coap.(*ClientCommander).newGetDeleteRequest(0xc0000108c0, 0x121f26a, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/gh0st42/go/pkg/mod/github.com/go-ocf/go-coap@v0.0.0-20181204124429-322e1f81bfdc/clientcommander.go:33 +0x15b
github.com/go-ocf/go-coap.(*ClientCommander).NewGetRequest(0xc0000108c0, 0x121f26a, 0x1, 0x0, 0x0, 0x0, 0x0)
	/Users/gh0st42/go/pkg/mod/github.com/go-ocf/go-coap@v0.0.0-20181204124429-322e1f81bfdc/clientcommander.go:60 +0x44
github.com/go-ocf/go-coap.(*ClientCommander).Get(0xc0000108c0, 0x121f26a, 0x1, 0xc00008cae0, 0x0, 0x0, 0xc000082180)
	/Users/gh0st42/go/pkg/mod/github.com/go-ocf/go-coap@v0.0.0-20181204124429-322e1f81bfdc/clientcommander.go:116 +0x43
github.com/go-ocf/go-coap.(*ClientConn).Get(0xc00008cae0, 0x121f26a, 0x1, 0xc, 0xc00008cae0, 0x0, 0x0)
	/Users/gh0st42/go/pkg/mod/github.com/go-ocf/go-coap@v0.0.0-20181204124429-322e1f81bfdc/client.go:311 +0x7c
main.main()
	/Users/gh0st42/Code/go/copperminer/cmds/coap.go:21 +0xe9
exit status 2
```

**Comment by jkralik** [comment]
Thx for find a bug.

By RFC it must be supported: https://tools.ietf.org/html/rfc7252#section-6.5 point 7 + https://tools.ietf.org/html/rfc7252#section-6.4 point 8

**Comment by jkralik** [comment]
I created pull request https://github.com/go-ocf/go-coap/pull/25 to fix the bug. Pls could you check the fix. Thx

**Comment by gh0st42** [comment]
Seems to work on, tried it with `Get("")` and `Get("/")`.
At least it works with `coap.Dial("udp", "coap.me:5683")`, interestingly I get an error when using `coap.Dial("udp", "californium.eclipse.org:5683")`

```
2018/12/06 23:39:57 Error sending request: write udp 192.168.2.103:63670: sendmsg: socket is not connected
```

The server itself works flawless when using for example cf-browser. Will open another issue for this.

**Comment by jkralik** [comment]
Please if there is still problem with:
`2018/12/06 23:39:57 Error sending request: write udp 192.168.2.103:63670: sendmsg: socket is not connected`
create new issue thanks.
