### ISSUE TITLE
Register mcast serve and request mcast UDP and UDP at the same time, unable to resolve ordinary UDP URI

### ISSUE THREAD

**Issue by Ternence** [go-ocf/go-coap#30]
We registered mcast server and set URI of interest. But after business logic receives the first mcast, it receives ordinary UDP packets. However, ordinary UDP package URIs have been unable to parse successfully, resulting in the inability to handle to the corresponding method. Find out the reason: We started mcast service, ordinary UDP request on the server selected UDP path, resulting in our registered URI Map in UDP package parsing URI MAP is empty, so can not match URI and Handle Method. The server of mcast chooses the URI-MAP of mcast, which can have our registered URI, and can match to URI and method normally.

To solve this problem, you need to merge serves locally or queue read consumption when listening. Or is there any other way of using it to support us in the business of mcast UDP and UDP at the same time?

```
z:map[.well-known/core:{0x17e0f4 .well-known/core} .sys/sessMngr:{0x17e500 .sys/sessMngr}]E
and 
z:map[]E

```
```
handleBlockWiseMsg 4 : <nil>  
handleBlockWiseMsg r.msg=&{{0 2 5056 [147 174] [123 34 116 121 112 101 34 58 49 44 34 109 111 100 101 83 117 112 112 111 114 116 34 58 49 44 34 115 110 49 34 58 34 52 53 52 49 52 49 55 51 54 56 52 54 54 97 52 99 34 44 34 115 101 113 34 58 50 54 50 54 52 125] [{11 .sys} {11 sessMngr}]}}
handleBlockWiseMsg CON 
handleBlockWiseMsg 1 : <nil>  
handleBlockWiseMsg 2 : <nil>  
handleBlockWiseMsg 3 : (func(coap.ResponseWriter, *coap.Request))(0x17bf80)  
z:map[]E
update:E
match:E
match default : 
handleBlockWiseMsg 4 : <nil>  
handleBlockWiseMsg r.msg=&{{1 1 5057 [59 224] [] [{11 .well-known} {11 core} {15 st=homeCenter}]}}
z:map[.well-known/core:{0x17e0f4 .well-known/core} .sys/sessMngr:{0x17e500 .sys/sessMngr}]E
match:.well-known/coreE
2019/01/04 23:08:01 Got message in handleMcast: path=[".well-known" "core"]: &coap.DgramMessage{MessageBase:coap.MessageBase{typ:0x1, code:0x1, messageID:0x13c1, token:[]uint8{0x3b, 0xe0}, payload:[]uint8{}, opts:coap.options{coap.option{ID:0xb, Value:".well-known"}, coap.option{ID:0xb, Value:"core"}, coap.option{ID:0xf, Value:"st=homeCenter"}}}} from 192.168.2.20:5683
```

**Comment by jkralik** [comment]
If I understand you have a server that listen on mcast (go-coap) and when a client (go-coap??) send mcast request, response doesn't arrived to the client. (it is stripped). For this purpose, the server can create a new connection to the client in a handler and the response is send via the connection. Something similar is implemented here https://github.com/go-ocf/go-coap/blob/12af0ac7561c257f7d4bb0162d076725241cb67c/server_test.go#L400

For more investigate issue,  could you provide me debug output of blockwise from the client/ the server: just set https://github.com/go-ocf/go-coap/blob/12af0ac7561c257f7d4bb0162d076725241cb67c/blockwise.go#L12 to `true` and repeat scenario.

**Comment by Ternence** [comment]
Thank you for your reply.
I tried it with examples. The previous steps all goes well, but when setting up the UDP server, it is error to say that the address and port have been in ues.

```
//First Step:
log.Fatal(ListenAndServe("238.238.238.238:5683", "udp-mcast", mux))
//Second Step:
func handleMcast(w ResponseWriter, r *Request) {
        // on receive mcast
        co, err := Dial("udp", "192.168.2.20:5683")
        // request NON.
	co.WriteMsg(req)

        // start new server to listen
	s, _, fin, err := RunLocalServerUDPWithHandler(lnet, addrMcast, BlockWiseTransfer, BlockWiseTransferSzx, func(w ResponseWriter, r *Request) {
}()
}
```

And the Error Image Here: 
![image](https://user-images.githubusercontent.com/2890392/50899720-e9db2000-144d-11e9-9524-19c433bc73cb.png)
unable to run test server: listen udp 192.168.2.16:5683: bind: address already in use
unable to run test server: listen udp 0.0.0.0:5683: bind: address already in use


![image](https://user-images.githubusercontent.com/2890392/50900130-265b4b80-144f-11e9-9d19-f27ec3d5deab.png)

I want to return to the ACK. However, as you can see, the return is based on receiving the other party's multicast and waiting for me to send a NON request. The other party just sent me a request, I want to reply ACK at this time.

What do you think I should do better? The problem I'm facing now is that I can't build up the last UDP Server. 
TKS.

**Comment by jkralik** [comment]
Dial must be called with `r.Client.RemoteAddr().String()` and you don't need to create such as server. I extend example for mcast/{server,client}: https://github.com/go-ocf/go-coap/blob/mcastPublishMsg/examples/mcast/server/main.go . Could you apply similar code on your project?

**Comment by Ternence** [comment]
HI, Jkralik.
In order to achieve our goal, we continued the original plan.
Step 1, our server replies to multicast
Step 2: Client sends us a CON request
Step 3, our server parses its CON request and replies to ACK  (error here )
![image](https://user-images.githubusercontent.com/2890392/50970487-76ecaa80-151c-11e9-9da3-f782c0542958.png)
As my first question, the Matching-Handles-Module cannot match it to the correct handle method. So we are forced to set the default handle to our processing service handle. (Test Only)
![image](https://user-images.githubusercontent.com/2890392/50970210-b9fa4e00-151b-11e9-8a55-df617658413d.png)
Then we found that logic worked. But the decoding of btyes has some problems.  the MSG was not parsed successfully（As shown in the following log）
```
handleBlockWiseMsg r.msg=&{{1 1 16075 [37 159] [] [{11 .well-known} {11 core} {15 st=homeCenter}]}}

srv:[&{238.238.238.238:5683 udp-mcast <nil> <nil> 0x11c70300 0x11c780e0 1152 1h0m0s 1h0m0s <nil> 0s 0x179814 0x1796f0 0x179940 0x179950 [] <nil> 0x11cbe99c 0 0 {{} <nil> 0 <nil>} {{} <nil> 0 <nil>} 0x11c6e0c0 0 {{0 0} 0 0 0 0} true {0 0} map[192.168.2.20:5683-GAAAAAAAAAAIAAAAAwAAAMCoAhDu7u7u:0x11cf6000]}],handler[&{map[.well-known/core:{0x17dc80 .well-known/core} .sys/sessMngr:{0x17e08c .sys/sessMngr}] 0x11c86240 0x174388}]
path:[.well-known/core]
mux len[2],z:[map[.well-known/core:{0x17dc80 .well-known/core} .sys/sessMngr:{0x17e08c .sys/sessMngr}]]

2019/01/10 20:35:49 Got message in handleMcast: path=[".well-known" "core"]: &coap.DgramMessage{MessageBase:coap.MessageBase{typ:0x1, code:0x1, messageID:0x3ecb, token:[]uint8{0x25, 0x9f}, payload:[]uint8{}, opts:coap.options{coap.option{ID:0xb, Value:".well-known"}, coap.option{ID:0xb, Value:"core"}, coap.option{ID:0xf, Value:"st=homeCenter"}}}} from 192.168.2.20:5683
2019/01/10 20:35:49  ====== req type : NonConfirmable
￼

second request 

handleBlockWiseMsg r.msg=&{{0 2 16076 [251 254] [123 34 116 121 112 101 34 58 49 44 34 109 111 100 101 83 117 112 112 111 114 116 34 58 49 44 34 115 110 49 34 58 34 52 53 53 52 53 57 52 50 52 100 53 53 54 49 54 100 34 44 34 115 101 113 34 58 52 55 48 50 50 125] [{11 .sys} {11 sessMngr}]}}
2019/01/10 20:35:49 receivePayload 0x11cf61f8 req=&{{0 95 16076 [251 254] [] [{27 6}]}}
2019/01/10 20:35:49 receivePayload 0x11cf61f8 resp=&{{0 0 0 [] [] []}}
srv:[&{ udp <nil> <nil> 0x11cf61c0 <nil> 1152 1h0m0s 1h0m0s 0x178874 0s 0x178a48 0x178a1c 0x179940 0x1789d0 [] 0x11cf0290 0x11cf0291 0 0 {{} <nil> 0 <nil>} {{} <nil> 0 <nil>} 0x11cf2440 0 {{0 0} 0 0 0 0} true {0 0} map[192.168.2.20:5683-GAAAAAAAAAAIAAAAAwAAAMCoAhDAqAIQ:0x11cf61f8]}],handler[<nil>]
path:[]
mux len[0],z:[map[]]
match default : 
 2019/01/10 20:35:49 sendPayload 0x11cf61f8 req=&{{2 132 0 [] [] [{28 0} {23 6}]}}
2019/01/10 20:35:49 sendPayload 0x11cf61f8 resp=&{{0 0 0 [] [] []}}

```
Finally, we found that the first MSG was not delivered correctly when dealing with block packets.
After commenting out the block logic, we're done correctly.
![image](https://user-images.githubusercontent.com/2890392/50975654-13b54500-1529-11e9-9d0c-1a2b5c788bcd.png)

Is there an error passing to the following MSG while waiting for other block data?

**Comment by jkralik** [comment]
OK. I found the bug in handle of POST/PUT request in receivePayload. If they don't contains options block2/block1 they were handled as they contained it.

Fixed in branch
https://github.com/go-ocf/go-coap/tree/fixServingUDPBlockWiseWithClientWithoutBlockWise

Pls could you verify it is fix your issue?
Thx

**Comment by jkralik** [comment]
I will close issue. If you still have problem reopen it. Thx
