### ISSUE TITLE
[Observable] Set CON/NON for notifications

### ISSUE THREAD

**Issue by palsivertsen** [go-ocf/go-coap#32]
[RFC7641](https://tools.ietf.org/html/rfc7641#section-3.5) states:
> A notification can be confirmable or non-confirmable, i.e., it can be
   sent in a confirmable or a non-confirmable message.  The message type
   used for a notification is independent of the type used for the
   request and of any previous notification.

The [ResponseWriter](https://godoc.org/github.com/go-ocf/go-coap#ResponseWriter) and [Message](https://godoc.org/github.com/go-ocf/go-coap#Message) interfaces are both missing an option to set the type of a message to CON/NON.

Is there a way to set message type for a notification when responding to a observe request?

**Comment by jkralik** [comment]
Request contains client that provides call `NewMessage`. 
Eg:
 ```
req.Client.NewMessage(coap.MessageParams{
		Type:  NonConfirmable,
		...
})```

Is it helps you?

**Comment by palsivertsen** [comment]
Shouldn't `coap.ResponseWriter.WriteMsg` if there's no ACK of a CON message?

I'm running the observe client/server example like so:
server/main.go:
```
....
func sendResponse(w coap.ResponseWriter, req *coap.Request, subded time.Time) error {
  resp := req.Client.NewMessage(coap.MessageParams{
    Type: coap.Confirmable,
    Code: coap.Content,
  })  
  resp.SetOption(coap.ContentFormat, coap.TextPlain)
  resp.SetObserve(5)
  resp.SetPayload([]byte(fmt.Sprintf("Been running for %v", time.Since(subded))))
  return w.WriteMsg(resp)
}
...
```

**Comment by jkralik** [comment]
But i think you need to set Token and MessageId(for udp) because the client cannot pair notification.....
```
func sendResponse(w coap.ResponseWriter, req *coap.Request, subded time.Time) error {
  resp := req.Client.NewMessage(coap.MessageParams{
    Type: coap.Confirmable,
    Code: coap.Content,
    MessageID: req.Msg.MessageID(),
    Token:     req.Msg.Token(),
  })  
  resp.SetOption(coap.ContentFormat, coap.TextPlain)
  resp.SetObserve(5)
  resp.SetPayload([]byte(fmt.Sprintf("Been running for %v", time.Since(subded))))
  return w.WriteMsg(resp)
}
...

**Comment by jkralik** [comment]
I will close this issue. Please if you have still problem please reopen it. Thx
