### ISSUE TITLE
RFC7967 Implementation

### ISSUE THREAD

**Issue by arun1587** [go-ocf/go-coap#35]
[RFC7967](https://datatracker.ietf.org/doc/rfc7967/), a new coap option called `No-Response` would be useful to tell the server explicitly to suppress the responses for any particular request from the server.

**Comment by jkralik** [comment]
Thank you for suggestion. Please if you have time - could you contribute and make merge request ?

**Comment by arun1587** [comment]
ok, do you have any guideline for raising a PR?

**Comment by jkralik** [comment]
Thx for contributing. PR: https://github.com/go-ocf/go-coap/pull/37
