### ISSUE TITLE
Message Type Confirmable instead of Acknowledge during Block-wise transfer

### ISSUE THREAD

**Issue by daniellouda** [go-ocf/go-coap#40]
CoAP server (examples/simple/server/main.go) on payload bearing POST request using block-wise transfer is responding with Message Type Confirmable instead of Acknowledge. Example of transfer follows.

Sending to server:
Confirmable POST Request, Options: Block[1:0/1/128] and Size[1:300]
```
0000   48 02 b3 44 35 cb d3 f8 5f a4 64 76 d1 0e 0b d2
0010   14 01 2c ff 61 61 61 61 61 61 61 61 61 61 61 61
0020   61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61
0030   61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61
0040   61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61
0050   61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61
0060   61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61
0070   61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61
0080   61 61 61 61 61 61 61 61 61 61 61 61 61 61 61 61
0090   61 61 61 61
```

Response from server:
Type - Confirmable, Code[2.31], Options: Block[1:0/1/128]
`0000   48 5f b3 44 35 cb d3 f8 5f a4 64 76 d1 0e 0b`

**Comment by jkralik** [comment]
Thank you for report issue. It was fixed by commit https://github.com/go-ocf/go-coap/commit/024bc1ece6fed01bdff9bb22826fc2f80f8316a6

I will close issue. If you still have problem reopen it. Thx
