### ISSUE TITLE
Custom options

### ISSUE THREAD

**Issue by alexryd** [go-ocf/go-coap#44]
Thanks for a great piece of software!
I’ve started using this library to communicate with an IoT device but I ran in to an issue. The device uses some non-standard options to convey certain pieces of information, but this library seems to simply omit any options that aren’t among the ones hardcoded. Looking at the code there doesn’t seem to be any chance of catching those custom options. Is there a reason it’s designed this way?

**Comment by jkralik** [comment]
It is legacy from `https://github.com/dustin/go-coap` . I think it is good feature.
Fill free to change options and create PR.

I can implement it in future, but right now, i m busy with OCF Cloud.

**Comment by alexryd** [comment]
Ok thanks! Then I’ll try to create a PR. Just wanted to make sure this wasn’t a deliberate decision to comply with some RFC.

**Comment by jkralik** [comment]
Implemented by https://github.com/go-ocf/go-coap/pull/76
