### ISSUE TITLE
Move Server out from Connection to Client 

### ISSUE THREAD

**Issue by cizmazia** [go-ocf/go-coap#45]
For transparent control over Server's lifetime, its lifetime should be managed by the Client instead of the Connection.

When `MulticastClientConn` is closed, it shuts the Server down even for the connections of responses to `PublishMsgWithContext`.  These connections are kept open for extended periods for further communication.

**Comment by jkralik** [comment]
Fixed with go-coap/v2. Feel free to reopen if your request is not satisfied.
