### ISSUE TITLE
WriteMsg

### ISSUE THREAD

**Issue by georges-honore-figfi** [go-ocf/go-coap#58]
Dear go-coap developers,
I am trying to use WriteMsg, with a timeout.
I set DialTimeout, WriteTimeout, ReadTimeout on client
and the message is POST & NonConfirmable.
I need the WriteMsg not to block forever when the unit is off the mesh (Powered down).
But it still hangs with these settings. I suspect I have missed a setting, but cannot
see what. It would be useful if one of the examples included setting timeouts.
Thank you for your time.

**Comment by jkralik** [comment]
Hi.
If you want to use timeout per request, you need to call functions with suffix "WithContext".
`ExchangeWithContext, WriteMsgWithContext, PingWithContext` and via context you can set timeout.
I will update simple example to use them.

Example:
`ctx, cancelTimeout := context.WithTimeout(context.Background(), 5*time.Second)`
`defer cancelTimeout()`
`err := conn.WriteMsgWithContext(ctx, msg)`

**Comment by georges-honore-figfi** [comment]
Jkralik,
Thank you this works for me.
Best regards

**Comment by jkralik** [comment]
I updated README.md and simple example about using context with timeout. Thank you for your feedback.
