### ISSUE TITLE
Panic using RSA keys with CoAP DTLS listener

### ISSUE THREAD

**Issue by hjames9** [go-ocf/go-coap#69]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x612897]

goroutine 35 [running]:
gitlab.com/hjames9/coapter/vendor/github.com/pion/dtls.(*Conn).Read(0x0, 0xc000164000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/home/hjames/.gvm/pkgsets/go1.13.3/global/src/gitlab.com/hjames9/coapter/vendor/github.com/pion/dtls/conn.go:253 +0x37
gitlab.com/hjames9/coapter/vendor/github.com/go-ocf/go-coap/net.(*ConnDTLS).readLoop(0xc00015c000)
	/home/hjames/.gvm/pkgsets/go1.13.3/global/src/gitlab.com/hjames9/coapter/vendor/github.com/go-ocf/go-coap/net/connDTLS.go:29 +0xdb
created by gitlab.com/hjames9/coapter/vendor/github.com/go-ocf/go-coap/net.NewConnDTLS
	/home/hjames/.gvm/pkgsets/go1.13.3/global/src/gitlab.com/hjames9/coapter/vendor/github.com/go-ocf/go-coap/net/connDTLS.go:52 +0xff
```

Loaded CoAP in DTLS mode with RSA keys
```
keys, err := tls.LoadX509KeyPair("certs/coapter_cert_rsa_2048.pem", "certs/coapter_key_rsa_2048.pem")
if err != nil {
	log.Fatal().Err(err).Send()
	return
}
certificate, err := x509.ParseCertificate(keys.Certificate[0])
if err != nil {
	log.Fatal().Err(err).Send()
	return
}
privateKey := keys.PrivateKey

config := &dtls.Config{
	Certificate:           certificate,
	PrivateKey:            privateKey,
	ExtendedMasterSecret:  dtls.RequireExtendedMasterSecret,
	ConnectTimeout:        dtls.ConnectTimeoutOption(30 * time.Second),
	InsecureSkipVerify:    true,
	VerifyPeerCertificate: certVerify,
	ClientAuth:            dtls.RequireAnyClientCert,
}
...
mux := coap.NewServeMux()
err = mux.Handle("/test", coap.HandlerFunc(handleCoapTest))
if err != nil {
	log.Fatal().Err(err).Send()
	return
}

err = coap.ListenAndServeDTLS("udp-dtls", ":5688", config, mux)
if err != nil {
	log.Error().Err(err).Send()
}
```
When the listener receives a DTLS message on the wire, it panics due to the DTLS connection object not being initialized properly due to setting up with RSA certs.  This should fail more gracefully in the ListenAndServerDTLS function instead of the panic.

It's correctly handled by DialDTLS() function where I receive "dtls: invalid private key type" error message.
The reason for that is that DialDTLS() creates the DTLS connection object via pion/dtls.Dial(), which eventually calls a function called createConn that has the key type check:
https://github.com/pion/dtls/blob/master/conn.go#L101

The listener code however, directly creates a dtls.Server object
https://github.com/go-ocf/go-coap/blob/92481866bd1713e2c98a02933f472c0f8a28a91c/server.go#L105
This bypasses all the sanity checks that exist in the pion/dtls library creating the server DTLS server connection object
https://github.com/pion/dtls/blob/master/conn.go#L240

Do you agree with this assessment?  I can help submit a PR to change this behaviour if you think this is the correct approach.

Thanks!

**Comment by jkralik** [comment]
Thx for finding bug.
I created PR https://github.com/go-ocf/go-coap/pull/70 which fix issue.

**Comment by hjames9** [comment]
@jkralik Thanks, this fixes the panic.  I now get an error instead when receiving a DTLS message:
"cannot serve dtls: cannot accept connections: dtls: invalid private key type"

Do you think it's better to get this error on receiving a message or immediately when just calling Listen() without needing an external message?

**Comment by jkralik** [comment]
@hjames9 I agree that listen must report error but it must be fixed in function `dtls.Listen` in package `pion/dtls`. Pls could you report them issue / create PR to fix it ?

**Comment by hjames9** [comment]
@jkralik You're right, took a look at the dtls.Listen code and it should be validating the dtls.Config object.  I'll submit a request with them and let you know when it's fixed.   Thanks!

**Comment by hjames9** [comment]
@jkralik FYI, got the DTLS Listen change merged into master

**Comment by hjames9** [comment]
@jkralik Changes are on tag 1.5.4 of pion/dtls.  Should I submit a PR for the version change to close this out?

**Comment by jkralik** [comment]
Thx for contributing. Now it is in master.

Good job! 👍
