### ISSUE TITLE
Why skip unrecognized options?

### ISSUE THREAD

**Issue by duanxuelin** [go-ocf/go-coap#71]
As described in the documentation RFC7252:

> The IANA policy for future additions to this sub-registry is split
   into three tiers as follows.  The range of 0..255 is reserved for
   options defined by the IETF (IETF Review or IESG Approval).  The
   range of 256..2047 is reserved for commonly used options with public
   specifications (Specification Required).  The range of 2048..64999 is
   for all other options including private or vendor-specific ones,
   which undergo a Designated Expert review to help ensure that the
   option semantics are defined correctly.  The option numbers between
   65000 and 65535 inclusive are reserved for experiments.  They are not
   meant for vendor-specific use of any kind and MUST NOT be used in
   operational deployments.  

We can define options in range of 2048..64999 for private use. So is there any way we can edit optionDefs for private options?

**Comment by duanxuelin** [comment]
Could it be possible that `func parseOptionValue` return valueBuf rather than nil for those unrecognized options?

**Comment by jkralik** [comment]
Yes. I think, it will be works. Could you pls provides PR with tests?

**Comment by duanxuelin** [comment]
I'd like to have a try.

**Comment by jkralik** [comment]
Thx for contrinting!
