### ISSUE TITLE
Optional blockwise transfer for udp

### ISSUE THREAD

**Issue by str4t0m** [go-ocf/go-coap#79]
When we connect to a node with UDP via DialWithContext, blockwise transfer is automatically enabled.
I have not seen an easy option to disable the block wise transfer, but would need it as the other device does not support blockwise transfer.

Could you imagine adding that as an argument?
Or is it already somehow possible?

**Comment by jkralik** [comment]
Sure. Just create instance of Client struct set `BlockWiseTransfer` to false. eg:
```
bw := false
client := Client{
   Net: "udp",
   BlockWiseTransfer: &bw,
}
con, err := client.DialWithContext(ctx, "myhost")
```

**Comment by str4t0m** [comment]
Thanks!
I have overlooked that.
