### ISSUE TITLE
Example Block-wise Transfer

### ISSUE THREAD

**Issue by georges-honore-figfi** [go-ocf/go-coap#85]
Would it be possible to add an example of the use of Block-wise Transfer to the examples.
I am trying to transfer a binary file to an end-device, and am trying to make use of
this feature.

**Comment by jkralik** [comment]
Blockwise is enabled by default for udp protocol. Just use https://github.com/go-ocf/go-coap/blob/master/examples/simple/server/main.go and set payload to content of file - streaming interface is not supported now.

**Comment by jkralik** [comment]
If you need more information just reopen issue.

**Comment by sinfere** [comment]
@jkralik could you provide examples for how to download file? have tried for long but failed

**Comment by sinfere** [comment]
error in client side:
```go
 Error sending request: cannot exchange: cannot write to udp connection: write udp 127.0.0.1:64755: sendmsg: socket is not connected
```

**Comment by IHIDCHAOS** [comment]
Hello @jkralik, I also want to transfer a binary file to an end-device, but don't know how to start with this library, could you please give me some advice and examples on this , many thanks in advance!
