### ISSUE TITLE
connect to coap server with specific source port

### ISSUE THREAD

**Issue by atreya2011** [go-ocf/go-coap#90]
I would like to know if there is a way to create a new client, by specifying a specific UDP source port like how we do with the net package. 

```
        server, _ := net.ResolveUDPAddr("udp", "google.com:80")
        client, _ := net.ResolveUDPAddr("udp", ":50000")
        conn, err := net.DialUDP("tcp", client, server)
```

Right now, the API does not seem to provide a way to specify the UDP port to send requests.

**Comment by jkralik** [comment]
For now it is not supported but you can contribute the feature.

**Comment by atreya2011** [comment]
Thank you for your quick response. I will look into it then. :)
