### ISSUE TITLE
blockwise observe

### ISSUE THREAD

**Issue by emidiocroci** [go-ocf/go-coap#99]
We are trying to observe a resource with blockwise enabled on UDP, but we receive only the first block. The client doesn't send the second request with block option 2 . We simply create a request with client.ObserveWithContext.... Are we missing something?

**Comment by jkralik** [comment]
Hi.  It is same issue https://github.com/go-ocf/go-coap/issues/12 - it was not implemented yet but we want to fix it in May/June.
